In [2]:
# Bibliotecas

import pandas as pd
import numpy  as np

## Leitura de arquivo

In [65]:
# Diretorio dos datasets C:\Users\Samsung

df = pd.read_csv('C:/Users/Samsung/Datasets/Kaggle/raw_data.csv')

C:\Users\Samsung\AppData\Local\Temp\ipykernel_15072\790349793.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('C:/Users/Samsung/Datasets/Kaggle/raw_data.csv')

In [66]:
df.head(10)

,Unnamed: 0,departamento,municipio,codigo_dane,armas_medios,fecha_hecho,genero,grupo_etario,cantidad
0,0,ATLÁNTICO,BARRANQUILLA (CT),8001000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,MASCULINO,ADULTOS,1
1,1,BOYACÁ,DUITAMA,15238000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,FEMENINO,ADULTOS,1
2,2,CAQUETÁ,PUERTO RICO,18592000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,MASCULINO,ADULTOS,1
3,3,CASANARE,MANÍ,85139000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,FEMENINO,ADULTOS,1
4,4,CUNDINAMARCA,BOGOTÁ D.C. (CT),11001000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,FEMENINO,ADULTOS,1
5,5,SUCRE,SINCELEJO (CT),70001000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,FEMENINO,ADULTOS,1
6,6,VALLE,CALI (CT),76001000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,FEMENINO,ADULTOS,2
7,7,VALLE,CALI (CT),76001000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,MASCULINO,ADULTOS,2
8,8,VALLE,TULUÁ,76834000,ARMA BLANCA / CORTOPUNZANTE,1/01/2010,FEMENINO,ADULTOS,1
9,9,HUILA,PITALITO,41551000,ARMA DE FUEGO,1/01/2010,FEMENINO,ADULTOS,1

### Renomear colunas

In [67]:
# Renomenado algumas colunas

df = df.rename({'armas_medios': 'arma_usada',
               'fecha_hecho':'data_crime',
                'genero': 'gênero',
               'cantidad': 'quantidade'}, axis=1)

In [68]:
#Excluir coluna

df = df.drop(['Unnamed: 0', 'codigo_dane'], axis=1)

In [52]:
#Informações do dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575721 entries, 0 to 575720
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   departamento  575721 non-null  object
 1   municipio     575721 non-null  object
 2   arma_usada    575721 non-null  object
 3   data_crime    575721 non-null  object
 4   gênero        575721 non-null  object
 5   grupo_etario  574110 non-null  object
 6   quantidade    575721 non-null  int64
dtypes: int64(1), object(6)
memory usage: 30.7+ MB

In [39]:
#Dimensão do dataframe
df.shape

(575721, 7)

In [21]:
# Verificando valores nulos e quantidade
df.isnull().sum()

departamento       0
municipio          0
arma_usada         0
data_crime         0
gênero             0
grupo_etario    1611
quantidade         0
dtype: int64

### Converter tipo de colunas

In [69]:
# Mudar o tipo de variável
# df['gênero'] = df['gênero'].astype('category')
# df['grupo_etario'] = df['grupo_etario'].astype('category')
# df['arma_usada'] = df['arma_usada'].astype('category')
df['data_crime'] = pd.to_datetime(df['data_crime'], format = '%d/%m/%Y')

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 575721 entries, 0 to 575720
Data columns (total 7 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   departamento  575721 non-null  object
 1   municipio     575721 non-null  object
 2   arma_usada    575721 non-null  object
 3   data_crime    575721 non-null  datetime64[ns]
 4   gênero        575721 non-null  object
 5   grupo_etario  574110 non-null  object
 6   quantidade    575721 non-null  int64
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 30.7+ MB

In [55]:
# Contagem de pessoas por departamento
df['departamento'].value_counts()

departamento
CUNDINAMARCA          104692
ANTIOQUIA              70655
VALLE                  53718
SANTANDER              45307
BOYACÁ                 32125
ATLÁNTICO              21253
TOLIMA                 21103
HUILA                  19966
META                   19841
BOLÍVAR                19159
NARIÑO                 17661
NORTE DE SANTANDER     17602
CAUCA                  17442
RISARALDA              16861
CÓRDOBA                13128
MAGDALENA              11812
SUCRE                  11580
CALDAS                 11082
CESAR                   9800
CASANARE                7520
QUINDÍO                 6001
CAQUETÁ                 5711
GUAJIRA                 5098
ARAUCA                  4314
PUTUMAYO                3882
CHOCÓ                   2570
AMAZONAS                1500
SAN ANDRÉS              1456
GUAVIARE                1214
GUAINÍA                  633
VAUPÉS                   523
VICHADA                  506
NO REPORTA                 6
Name: count, dtype: int64

In [70]:
df['municipio'].value_counts()

municipio
BOGOTÁ D.C. (CT)         58548
MEDELLÍN (CT)            25142
CALI (CT)                22048
BUCARAMANGA (CT)         11992
VILLAVICENCIO (CT)       11453
                         ...
CEPITÁ                       3
SÁCAMA                       3
BOJAYÁ                       2
ZAPAYÁN                      2
SAN JACINTO DEL CAUCA        2
Name: count, Length: 1023, dtype: int64

In [74]:
df['arma_usada'].value_counts()

arma_usada
CONTUNDENTES                   280171
SIN EMPLEO DE ARMAS            169055
NO REPORTADO                    76352
ARMA BLANCA / CORTOPUNZANTE     43570
ESCOPOLAMINA                     3863
ARMA DE FUEGO                    2710
Name: count, dtype: int64

In [73]:
df['arma_usada'].replace({'NO REPORTA': 'NO REPORTADO',
                          '-': 'NO REPORTADO',
                          'CORTANTES':'ARMA BLANCA / CORTOPUNZANTE',
                          'PUNZANTES':'ARMA BLANCA / CORTOPUNZANTE',
                          'CORTOPUNZANTES':'ARMA BLANCA / CORTOPUNZANTE'
                          }, inplace= True)

In [80]:
df['grupo_etario'].value_counts()

grupo_etario
ADULTOS         503613
ADOLESCENTES     35551
MENORES          34439
NO REPORTADO       507
Name: count, dtype: int64

In [79]:
df['grupo_etario'].replace('NO REPORTA', 'NO REPORTADO', inplace = True)

In [87]:
df['gênero'].value_counts()

gênero
FEMININO        437931
MASCULINO       137257
NO REPORTADO       533
Name: count, dtype: int64

In [86]:
df['gênero'].replace({'NO REPORTA': 'NO REPORTADO',
                      '-': 'NO REPORTADO',
                      'FEMENINO': 'FEMININO'}, inplace = True)

### Substituir valores da coluna

In [43]:
# # Substitui a categoria 'NO REPORTA' por NaN valor nulo
# df['departamento'].replace('NO REPORTA', np.nan)

In [13]:
# As linhas que contém valores nulos na coluna departamento são removidas,
# Resulta um DataFrame que contém apenas as linhas que não contêm valores nulos na coluna departamento.

df = df[~df['departamento'].isnull()]

In [14]:
# Localiza no DataFrame a coluna municipio e filtra o valor 'BOGOTA' e na coluna departameto substitui o valor 'SANTAFE'

df.loc[df['municipio']== 'BOGOTÁ D.C. (CT)', 'departamento'] = 'SANTAFE DE BOGOTA D.C'

In [15]:
#Substitui valores de um dataframe:

df['gênero'] = df['gênero'].replace({'NO REPORTADO':'NO REPORTA', '-':'NO REPORTA'})
df['grupo_etario'] = df['grupo_etario'].replace('NO REPORTADO', 'NO REPORTA')
df['arma_usada'] = df['arma_usada'].replace({'CONTUNDENTES':'ARMA BLANCA', 
                                            'ARMA BLANCA / CORTOPUNZANTE':'ARMA BLANCA', 
                                            'CORTOPUNZANTES':'ARMA BLANCA',
                                            'CORTANTES':'ARMA BLANCA', 
                                            'PUNZANTES':'ARMA BLANCA',
                                            'NO REPORTADO':'NO REPORTA', 
                                            '-':'NO REPORTA'})

In [16]:
#Imprime os valores únicos das colunas 
print(df['gênero'].unique(), 
      df['grupo_etario'].unique(), 
      df['arma_usada'].unique())

['MASCULINO', 'FEMENINO', 'NO REPORTA']
Categories (3, object): ['FEMENINO', 'MASCULINO', 'NO REPORTA'] ['ADULTOS', 'ADOLESCENTES', 'MENORES', 'NO REPORTA', NaN]
Categories (4, object): ['ADOLESCENTES', 'ADULTOS', 'MENORES', 'NO REPORTA'] ['ARMA BLANCA', 'ARMA DE FUEGO', 'NO REPORTA', 'SIN EMPLEO DE ARMAS', 'ESCOPOLAMINA']
Categories (5, object): ['ARMA BLANCA', 'ARMA DE FUEGO', 'ESCOPOLAMINA', 'NO REPORTA', 'SIN EMPLEO DE ARMAS']

In [17]:
# verificar outiler na coluna quantidade, absurdo quatidade>20, quantos casos tem outiler
#Cria um novo dataframe com apenas a coluna quantidade, onde os valores são maiores que 20

df[['quantidade']].query('quantidade > 20').count()

quantidade    3442
dtype: int64

In [18]:
# Cria um novo dataframe com as linhas com os valores da coluna quantidade < 20, exclui os index com esses valore
# e redefine os novos index do dataframe

df = df.query('quantidade < 20').reset_index(drop=True)

In [19]:
df

,Unnamed: 0,departamento,municipio,arma_usada,data_crime,gênero,grupo_etario,quantidade
0,0,ATLÁNTICO,BARRANQUILLA (CT),ARMA BLANCA,2010-01-01,MASCULINO,ADULTOS,1
1,1,BOYACÁ,DUITAMA,ARMA BLANCA,2010-01-01,FEMENINO,ADULTOS,1
2,2,CAQUETÁ,PUERTO RICO,ARMA BLANCA,2010-01-01,MASCULINO,ADULTOS,1
3,3,CASANARE,MANÍ,ARMA BLANCA,2010-01-01,FEMENINO,ADULTOS,1
4,4,SANTAFE DE BOGOTA D.C,BOGOTÁ D.C. (CT),ARMA BLANCA,2010-01-01,FEMENINO,ADULTOS,1
...,...,...,...,...,...,...,...,...
572068,575716,VALLE,CARTAGO,SIN EMPLEO DE ARMAS,2023-02-28,FEMENINO,ADULTOS,1
572069,575717,VALLE,GUACARÍ,SIN EMPLEO DE ARMAS,2023-02-28,FEMENINO,ADULTOS,1
572070,575718,VALLE,GUADALAJARA DE BUGA,SIN EMPLEO DE ARMAS,2023-02-28,FEMENINO,ADULTOS,1
572071,575719,VALLE,PALMIRA,SIN EMPLEO DE ARMAS,2023-02-28,FEMENINO,ADULTOS,2
572072,575720,VALLE,YUMBO,SIN EMPLEO DE ARMAS,2023-02-28,FEMENINO,ADULTOS,1

In [20]:
# Salvar o dataframe após a limpeza dos dados
df.to_csv('C:/Users/Samsung/Datasets/date_cleaned.csv')